### ISSUE TITLE
Request name not shown in tab list

### ISSUE THREAD

**Issue by marcvanbreemen** [AntonShuvaev/jet-client-support#73] opened 2024-05-15 07:44 UTC
Request name not shown in tab list. See screenshot.

<img width="1087" alt="image" src="https://github.com/AntonShuvaev/jet-client-support/assets/53403644/74902604-bf24-4dc4-a4ae-f9e66b852e9b">

**Environment information:**
- OS: Windows
- IDE version: Rider latest version
- plugin version: latest version

**Comment by AntonShuvaev** [comment] 2024-05-19 19:55
Hi @marcvanbreemen,

Thank you for reporting this issue.

I am unable to reproduce this problem. Could you please provide more details to help me investigate further? Specifically:

- Is it a persistent issue, or does it disappear?
- Does restarting the IDE resolve the issue?
- Do you have any steps to reproduce it?

**Comment by AntonShuvaev** [comment] 2024-05-21 19:19
Fixed in version 2024.2.3

**Closed by AntonShuvaev** 2024-05-21 19:19 UTC
Labels: bug
