### ISSUE TITLE
Problem with globals environment

### ISSUE THREAD

**Issue by erojaslabelgrup** [AntonShuvaev/jet-client-support#54] opened 2024-03-21 08:35 UTC
I have specified an environment variable in Globals and I am adding a double quote mark after the variable.
`{"local": {
    "base": "http://localhost:8000/api/"
  }}`

In the end what it executes is:

"http://localhost:8000/api/"ENDPOINT"

**Comment by stelianstoevSAP** [comment] 2024-03-21 09:39
**Describe the bug**
I have the same problem and would like to describe it in more detail, because it's a blocker.

With the latest version of the plugin (20 March) 2024.1.1-233 the global variables have received an extra set of double quotes. This kills the requests completely, since every variable 

**Steps to reproduce**
1. create a new env
2. use this values
`  bugreport: {
    http_port: 'https',
    url: 'localhost:8080',
    endpoint: 'bug_reported'
  }`
3. Launch a request to **{{http_port}}://{{url}}/{{endpoint}}**

<img width="942" alt="image" src="https://github.com/AntonShuvaev/jet-client-support/assets/159432003/509ef510-e26b-4792-bb58-02527482cf1d">

**Expected behavior**
It should not mess with the double quotes and resolve the variables to **https://localhost:8080/bug_reported**

**Environment information:**
- OS: MacOS 14.4
- IDE version: 2023.3.5
- plugin version: 2024.1.1-233

**Comment by KaVeKa** [comment] 2024-03-21 09:40
The problem is indeed not limited to global variables only. We are experiencing the same issue here :)

**Comment by AntonShuvaev** [comment] 2024-03-21 09:42
Thanks for reporting. Will fix ASAP

**Comment by AntonShuvaev** [comment] 2024-03-21 12:52
The issue has been resolved in version 2024.1.2

**Closed by AntonShuvaev** 2024-03-21 12:52 UTC
Labels: bug

**Comment by stelianstoevSAP** [comment] 2024-03-21 12:58
Thanks for the quick fix! Cheers
